import type { Metadata } from "next";
import { Manrope as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";
import { SideBar } from "@/components/side-bar";
import { ScrollArea } from "@/components/ui/scroll-area";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen flex bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <aside className="lg:flex">
          <SideBar className="relative hidden lg:flex" />
        </aside>
        <div className="flex flex-1">
          <ScrollArea className="flex flex-col" hasScrollTitle>
            {children}
          </ScrollArea>
        </div>
      </body>
    </html>
  );
}
