import {
  AmazonWebServicesDark,
  AmazonWebServicesLight,
  AmazonWebServicesUrl,
  Arc,
  ArcBrowserUrl,
  BetterAuthDark,
  BetterAuthLight,
  BetterAuthUrl,
  ClaudeAI,
  ClaudeAIUrl,
  Cloudflare,
  CloudflareUrl,
  Convex,
  ConvexUrl,
  CSS,
  CSSUrl,
  CursorDark,
  CursorLight,
  CursorUrl,
  DrizzleORMDark,
  DrizzleORMLight,
  DrizzleORMUrl,
  ExpressjsDark,
  ExpressjsLight,
  ExpressjsUrl,
  Figma,
  FigmaUrl,
  FramerDark,
  FramerLight,
  FramerUrl,
  GitHubDark,
  GitHubLight,
  GitHubUrl,
  GitLab,
  GitLabUrl,
  Hono,
  HonoUrl,
  HTML5,
  HTML5Url,
  JavaScript,
  JavaScriptUrl,
  Lovable,
  LovableUrl,
  ModelContextProtocolDark,
  ModelContextProtocolLight,
  ModelContextProtocolUrl,
  MongoDB,
  MongoDBUrl,
  MotionDark,
  MotionLight,
  MotionUrl,
  MySQL,
  MySQLUrl,
  Neon,
  NeonUrl,
  Nextjs,
  NextjsUrl,
  Nodejs,
  NodejsUrl,
  OpenAIDark,
  OpenAILight,
  OpenAIUrl,
  PerplexityAI,
  PerplexityAIUrl,
  PostgreSQL,
  PostgreSQLUrl,
  PrismaDark,
  PrismaLight,
  PrismaUrl,
  ReactLight,
  ReactQuery,
  ReactQueryUrl,
  ReactUrl,
  RemixDark,
  RemixLight,
  RemixUrl,
  Supabase,
  SupabaseUrl,
  TailwindCSS,
  TailwindCSSUrl,
  TRPC,
  TRPCUrl,
  TypeScript,
  TypeScriptUrl,
  Ubuntu,
  UbuntuUrl,
  VercelDark,
  VercelLight,
  VercelUrl,
} from '@ridemountainpig/svgl-react';
import { Icons, SocialIcons } from '@/components/icons';

export const PROFILES = {
  twitter: {
    title: 'X (Twitter)',
    username: 'jotyy',
    url: 'https://x.com/jotyy_ai',
    icon: <SocialIcons.x />,
  },
  github: {
    title: 'GitHub',
    url: 'https://github.com/jotyy',
    icon: <SocialIcons.github />,
  },
  linkedin: {
    title: 'LinkedIn',
    url: 'https://www.linkedin.com/in/jotyy3',
    icon: <SocialIcons.linkedin />,
  },
  readcv: {
    title: 'Read.cv',
    url: 'https://read.cv/jotyy',
    icon: <Icons.at />,
  },
};

export const LINKS = [
  {
    href: '/',
    label: 'Home',
    icon: <Icons.home />,
  },
  {
    href: '/works',
    label: 'Works',
    icon: <Icons.works />,
  },
  {
    href: '/skills',
    label: 'Skills',
    icon: <Icons.skills />,
  },
  {
    href: '/writing',
    label: 'Writing',
    icon: <Icons.blog />,
  },
  // {
  //   href: "/bookmarks",
  //   label: "Bookmarks",
  //   icon: <Icons.bookmark />,
  // },
  // {
  //   href: '/contact',
  //   label: 'Contact',
  //   icon: <Icons.contact />,
  // },
];

export const SCROLL_AREA_ID = 'scroll-area';
export const MOBILE_SCROLL_THRESHOLD = 20;

export const WORKS = [
  {
    title: 'Holaboss.ai',
    description: 'AI Agent platform for solo builders',
    href: 'https://holaboss.ai',
    cover: '/images/projects/holaboss-ai.webp',
    tags: ['Astro', 'Tailwind', 'shadcn/ui'],
  },
  {
    title: 'Holaboss Dashboard',
    description: 'AI Agent platform for solo builders',
    cover: '/images/projects/holaboss-dashboard.webp',
    tags: ['React Router', 'Hono.js', 'shadcn/ui'],
  },
  {
    title: 'iMerch.ai',
    description: 'AI Merch Portal Site',
    href: 'https://imerch.ai',
    cover: '/images/projects/imerch-ai.webp',
    tags: ['Next.js', 'TRPC', 'Motion'],
  },
  {
    title: 'iMerch Dashboard',
    description: 'Your AI Talent Manager & Monetization Platform',
    href: 'https://imerch.ai/dashboard',
    cover: '/images/projects/imerch-dashboard.webp',
    tags: ['Next.js', 'Tanstack Query', 'shadcn/ui'],
  },
  {
    title: 'Denser.ai',
    description: 'AI Portal Site',
    href: 'https://denser.ai',
    cover: '/images/projects/denser-ai.webp',
    tags: ['Next.js', 'Tailwind', 'shadcn/ui'],
  },
  {
    title: 'Denser Dashboard',
    description: 'Dashboard for denser.ai',
    href: 'https://denser.ai/u',
    cover: '/images/projects/denser-dashboard.webp',
    tags: ['React', 'Vite', 'shadcn/ui', 'Nest.js'],
  },
  {
    title: 'MegaETH Waitlist',
    description: 'Personal designed wait list page',
    href: 'https://mega-eth-landing.vercel.app/v1',
    cover: '/images/projects/megaeth-v1.webp',
    tags: ['Next.js', 'Design', 'Three.js'],
  },
  {
    title: 'MegaETH Landing',
    description: 'Personal designed landing page',
    href: 'https://mega-eth-landing.vercel.app/v3',
    cover: '/images/projects/megaeth-v3.webp',
    tags: ['Next.js', 'Design', 'Blur'],
  },
  {
    title: 'Lattice Browser',
    description: 'Blockchain Explorer',
    cover: '/images/projects/lattice-browser.png',
    tags: ['Next.js', 'GraphQL', 'Ethers'],
  },
  {
    title: 'Udun Wallet',
    description: 'Ethereum wallet',
    cover: '/images/projects/udun-wallet.png',
    tags: ['Flutter', 'Ethers.js', 'Rust'],
  },
];

export const STACKS = {
  languages: [
    { title: 'JavaScript', icon: JavaScript, url: JavaScriptUrl },
    { title: 'TypeScript', icon: TypeScript, url: TypeScriptUrl },
    { title: 'HTML', icon: HTML5, url: HTML5Url },
    { title: 'CSS', icon: CSS, url: CSSUrl },
    { title: 'NodeJs', icon: Nodejs, url: NodejsUrl },
    { title: 'SQL', icon: MySQL, url: MySQLUrl },
  ],
  frameworks: [
    { title: 'React', icon: ReactLight, url: ReactUrl },
    { title: 'NextJs', icon: Nextjs, url: NextjsUrl },
    { title: 'Remix', icon: RemixLight, darkIcon: RemixDark, url: RemixUrl },
    { title: 'HonoJs', icon: Hono, url: HonoUrl },
    {
      title: 'ExpressJs',
      icon: ExpressjsLight,
      darkIcon: ExpressjsDark,
      url: ExpressjsUrl,
    },
    { title: 'TailwindCSS', icon: TailwindCSS, url: TailwindCSSUrl },
    { title: 'TankStack Query', icon: ReactQuery, url: ReactQueryUrl },
    { title: 'TRPC', icon: TRPC, url: TRPCUrl },
    {
      title: 'Motion.dev',
      icon: MotionLight,
      darkIcon: MotionDark,
      url: MotionUrl,
    },
    {
      title: 'BetterAuth',
      icon: BetterAuthLight,
      darkIcon: BetterAuthDark,
      url: BetterAuthUrl,
    },
    {
      title: 'Drizzle',
      icon: DrizzleORMLight,
      darkIcon: DrizzleORMDark,
      url: DrizzleORMUrl,
    },
    {
      title: 'Prisma',
      icon: PrismaLight,
      darkIcon: PrismaDark,
      url: PrismaUrl,
    },
  ],
  ai: [
    {
      title: 'OpenAI',
      icon: OpenAILight,
      darkIcon: OpenAIDark,
      url: OpenAIUrl,
    },
    { title: 'Claude', icon: ClaudeAI, url: ClaudeAIUrl },
    { title: 'Perplexity', icon: PerplexityAI, url: PerplexityAIUrl },
    {
      title: 'Cursor',
      icon: CursorLight,
      darkIcon: CursorDark,
      url: CursorUrl,
    },
    {
      title: 'MCP',
      icon: ModelContextProtocolLight,
      darkIcon: ModelContextProtocolDark,
      url: ModelContextProtocolUrl,
    },
    {
      title: 'Lovable',
      icon: Lovable,
      url: LovableUrl,
    },
  ],
  databases: [
    { title: 'PostgreSQL', icon: PostgreSQL, url: PostgreSQLUrl },
    { title: 'MongoDB', icon: MongoDB, url: MongoDBUrl },
    { title: 'Supabase', icon: Supabase, url: SupabaseUrl },
    { title: 'Convex', icon: Convex, url: ConvexUrl },
    { title: 'NeonDB', icon: Neon, url: NeonUrl },
  ],
  devops: [
    {
      title: 'Github',
      icon: GitHubLight,
      darkIcon: GitHubDark,
      url: GitHubUrl,
    },
    {
      title: 'AWS',
      icon: AmazonWebServicesLight,
      darkIcon: AmazonWebServicesDark,
      url: AmazonWebServicesUrl,
    },
    {
      title: 'Vercel',
      icon: VercelLight,
      darkIcon: VercelDark,
      url: VercelUrl,
    },
    { title: 'Cloudflare', icon: Cloudflare, url: CloudflareUrl },
    { title: 'Ubuntu', icon: Ubuntu, url: UbuntuUrl },
    { title: 'Gitlab', icon: GitLab, url: GitLabUrl },
  ],
  software: [
    {
      title: 'Cursor',
      icon: CursorLight,
      darkIcon: CursorDark,
      url: CursorUrl,
    },
    { title: 'Arc', icon: Arc, url: ArcBrowserUrl },
    { title: 'Figma', icon: Figma, url: FigmaUrl },
    {
      title: 'Framer',
      icon: FramerLight,
      darkIcon: FramerDark,
      url: FramerUrl,
    },
  ],
  // devops: [
  //   { title: "Github Actions(CI/CD)", icon: "githubactions" },
  //   { title: "", icon: "jwt" },
  // ],
};
